"use client";

import { useEffect, useRef, useState } from "react";
import { Pause, Play } from "lucide-react";

/**
 * The spoken version of the hero line.
 *
 * Three decisions worth stating, because the obvious version of this component
 * is worse in all three.
 *
 * It does not autoplay. Every browser blocks unmuted autoplay, so the "working"
 * version of autoplay is a muted clip nobody hears, and the version that does
 * get through on a permissive browser is a stranger's voice in a quiet room.
 *
 * It removes itself if the file is missing. The audio is generated by a Python
 * tool that is not installed on the build machines, so a deploy can legitimately
 * ship without it. A dead control is worse than no control.
 *
 * It loads nothing until the first click. `preload="none"` keeps roughly 30 KB
 * off the critical path of the first page a visitor sees.
 */
export function HeroAudio() {
  const ref = useRef<HTMLAudioElement | null>(null);
  const [playing, setPlaying] = useState(false);
  const [available, setAvailable] = useState(true);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;

    const onEnded = () => setPlaying(false);
    const onPause = () => setPlaying(false);
    const onPlay = () => setPlaying(true);
    const onError = () => {
      setAvailable(false);
      setPlaying(false);
    };

    el.addEventListener("ended", onEnded);
    el.addEventListener("pause", onPause);
    el.addEventListener("play", onPlay);
    el.addEventListener("error", onError);

    return () => {
      el.removeEventListener("ended", onEnded);
      el.removeEventListener("pause", onPause);
      el.removeEventListener("play", onPlay);
      el.removeEventListener("error", onError);
      el.pause();
    };
  }, []);

  if (!available) return null;

  const toggle = () => {
    const el = ref.current;
    if (!el) return;
    if (el.paused) {
      // A rejected play() is almost always a missing or unplayable file.
      el.play().catch(() => setAvailable(false));
    } else {
      el.pause();
    }
  };

  return (
    <>
      <button
        type="button"
        onClick={toggle}
        aria-pressed={playing}
        className="inline-flex items-center gap-2 border-b border-transparent pb-0.5 font-mono text-[0.6875rem] uppercase tracking-[0.11em] text-[var(--hero-dim)] transition-colors hover:border-white/40 hover:text-[var(--hero-ink)]"
      >
        {playing ? (
          <Pause className="h-3 w-3" aria-hidden="true" />
        ) : (
          <Play className="h-3 w-3" aria-hidden="true" />
        )}
        {playing ? "Stop" : "Hear it"}
      </button>

      {/* The transcript, for anyone who cannot or would rather not play it.
          Audio that only exists as audio is a page that says less to some
          readers than to others. */}
      <p className="sr-only">
        Spoken introduction: I'm Balisa. I build AI systems that solve real problems in West Africa.
        This is my work.
      </p>

      {/* eslint-disable-next-line jsx-a11y/media-has-caption */}
      <audio ref={ref} src="/audio/hero.mp3" preload="none" />
    </>
  );
}
